version: '3'

services:
  php:
    build: ./
    depends_on:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
  user-db:
    container_name: user-db
    image: mysql:8.0
    volumes:
        - ./db/mysql_lib:/var/lib/mysql
        - ./db/mysql_conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - 33306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - user-db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=user-db
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    ports:
      - "3002:80"
    volumes:
      - ./docker/phpmy/sessions:/sessions
